spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/authorized
            scope:
              -openid
              -profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
        - id: microservice-oauth
          uri: lb://microservice-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2  #esto depende de tu ruta el mio tiene 2 niveles antes de los endpoints