spring:
  cloud:
    gateway:
      routes:
        - id: microservice-oauth
          uri: lb://microservice-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2  #esto depende de tu ruta el mio tiene 2 niveles antes de los endpoints