spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
        - id: microservice-oauth
          uri: lb://microservice-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: microservice-orders
          uri: lb://localhost:9092
          predicates:
            - Path=/api/order/**
        - id: microservice-registry
          uri: lb://localhost:9091
          predicates:
            - Path=/api/registry/**
        - id: microservice-inventory
          uri: lb://localhost:9093
          predicates:
            - Path=/api/products/**
        - id: microservice-sales
          uri: http://localhost:9090
          predicates:
             - Path=/api/sales/**