server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: microservice-gateway
  #security:
      # oauth2:
      #     resourceserver:
      # jwt:
      #   issuer-uri: http://127.0.0.1:9100
      #client:
      # registration:
      #   client-app:
      #     provider: spring
      #     client-id: gateway-app
      #     client-secret: 12345
      #     authorization-grant-type: authorization_code
      #     redirect-uri: http://127.0.0.1:8090/login/oauth2/code/client-app
      #     scope:
      #       - openid
      #       - profile
      #
      #     client-name: client-app
      # provider:
      #   spring:
    #     issuer-uri: http://127.0.0.1:9100

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3001'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowedCredentials: true
      discovery:
        locator:
          enabled: true
          # default-filters:
        # - TokenRelay
      routes:
        - id: microservice-registry
          uri: http://localhost:9091
          predicates:
              - Path=/api/registry/**
        - id: microservice-inventory
          uri: http://localhost:8090
          predicates:
            - Path=/api/products/**
        - id: microservice-sales
          uri: http://localhost:9090
          predicates:
            - Path=/api/sales/**
       # - id: microservice-oauth
       #   uri: lb://microservice-oauth
       #   predicates:
       #     - Path=/api/security/**
       #   filters:
       #     - StripPrefix=2
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
        - id: microservice-orders
          uri: http://localhost:9092
          predicates:
            - Path=/api/order/**
       #   filters:
       #     - StripPrefix=2
  #esto depende de tu ruta el mio tiene 2 niveles antes de los endpoints