spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
        - id: microservice-oauth
          uri: lb://microservice-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
